project_name: template

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: main
    binary: main
    main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - id: main
    builds:
      - main
    name_template: "main_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

gomod:
  proxy: true

release:
  draft: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo