# .github/workflows/main.yml

name: Test & Build

on:
  workflow_call:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: make test
      - uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Go Test Results
          path: .test/reports/**-test.xml
          reporter: java-junit
          fail-on-error: "true"
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Test Reports
          path: .test/reports/**

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
      - run: make lint

  deploy:
    if: success() && !contains( github.ref, 'dependabot' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npx cdktf-cli get

      - uses: hashicorp/terraform-cdk-action@v7
        with:
          cdktfVersion: 0.20.9
          terraformVersion: 1.9.5
          mode: auto-approve-apply
          stackName: stack
          githubToken: ${{ secrets.GITHUB_TOKEN }}
