name: "Plan"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    permissions:
      checks: write
    uses: ./.github/workflows/main.yml
    with:
      disable_deploy: ${{ github.actor == 'dependabot[bot]' }}
  plan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx cdktf-cli get
      - uses: hashicorp/terraform-cdk-action@v5
        with:
          cdktfVersion: 0.20.9
          terraformVersion: 1.9.5
          mode: plan-only
          stackName: stack
          githubToken: ${{ secrets.GITHUB_TOKEN }}
